// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Value_Conversions;

#nullable disable

namespace ValueConversions.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221219114454_mig_4")]
    partial class mig4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Value_Conversions.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Gender = "M",
                            Gender2 = "Male",
                            Name = "Ahmet"
                        },
                        new
                        {
                            Id = 2,
                            Gender = "M",
                            Gender2 = "Male",
                            Name = "Mehmet "
                        },
                        new
                        {
                            Id = 3,
                            Gender = "M",
                            Gender2 = "Male",
                            Name = "Ali"
                        },
                        new
                        {
                            Id = 4,
                            Gender = "F",
                            Gender2 = "Female",
                            Name = "Fatma"
                        },
                        new
                        {
                            Id = 5,
                            Gender = "F",
                            Gender2 = "Female",
                            Name = "Ayşe"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
